namespace: "tanzu-system-logging"
fluent_bit:
  config:
    service: |
      [Service]
        Flush               1
        Log_Level           info
        Daemon              off
        Parsers_File        parsers.conf
        HTTP_Server         On
        HTTP_Listen         0.0.0.0
        HTTP_Port           2020
    outputs: |
      [OUTPUT]
        Name                 syslog
        Match                *
        Host                 192.168.100.175 #vRLI host
        Port                 514 #vRLI port
        Mode                 tcp
        Syslog_Format        rfc5424
        Syslog_Hostname_key  cluster #Note that this corresponds to the Record_modifier filtering we did
        Syslog_Appname_key   pod_name
        Syslog_Procid_key    container_name
        Syslog_Message_key   message
        syslog_msgid_key     msgid
        Syslog_SD_key        k8s #Note that this corresponds to the Modifier filtering we did where we copied the kubernetes map to k8s
        Syslog_SD_key        labels
        Syslog_SD_key        annotations

    inputs: |
      [INPUT]
        Name                tail
        Path                /var/log/containers/*.log
        Parser              cri
        DB                  /var/log/flb_kube.db
        Tag                 kube.*
        Mem_Buf_Limit       5MB
        Skip_Long_Lines     On

      [INPUT]
        Name                systemd
        Tag                 host.*
        Systemd_Filter      _SYSTEMD_UNIT=kubelet.service
        Read_From_Tail      On
    filters: |
      [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix     kube.var.log.containers.
        Merge_Log           On
        Merge_Log_Key       log_processed
        K8S-Logging.Parser  On
        K8S-Logging.Exclude On

      [FILTER]
        Name                modify
        Match               *
        Rename message text
     [FILTER]
        Name                record_modifier
        Match               *
        Record cluster      #Name of the cluster
     [FILTER]
        Name                modify
        Match               kube.*
        Copy                kubernetes k8s
     [FILTER]
        Name                nest
        Match               kube.*
        Operation           lift
        Nested_Under        kubernetes
    parsers: |
      [PARSER]
        Name                json
        Format              json
        Time_Key            time
        Time_Format         %d/%b/%Y:%H:%M:%S %z
    streams: ""
    plugins: ""
  daemonset:
    resources: {}
    podAnnotations: {}
    podLabels: {}
